use_frameworks!

platform :ios, '8.0'

target 'JDCDefender_Example' do
  pod 'JDCDefender', :path => '../'

  target 'JDCDefender_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
